export enum ValidationCode {
  USERNAME_REQUIRED = 'USERNAME_REQUIRED',
  USERNAME_MIN = 'USERNAME_MIN',
  USERNAME_MAX = 'USERNAME_MAX',
  USERNAME_PATTERN = 'USERNAME_PATTERN',
  USERNAME_UNIQUE = 'USERNAME_UNIQUE',

  DESCRIPTION_MIN = 'DESCRIPTION_MIN',
  DESCRIPTION_MAX = 'DESCRIPTION_MAX',

  BIRTHDATE_REQUIRED = 'BIRTHDATE_REQUIRED',
  BIRTHDATE_ISO = 'BIRTHDATE_ISO',
  BIRTHDATE_INVALID = 'BIRTHDATE_INVALID',

  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  EMAIL_INVALID = 'EMAIL_INVALID',

  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
  PASSWORD_WEAK = 'PASSWORD_WEAK',

  UNSUPPORTED_CONTENT_TYPE = 'UNSUPPORTED_CONTENT_TYPE',

  CONTENT_LENGTH_INVALID = 'CONTENT_LENGTH_INVALID',
  CONTENT_LENGTH_MIN = 'CONTENT_LENGTH_MIN',
  CONTENT_LENGTH_MAX = 'CONTENT_LENGTH_MAX',

  AVATAR_KEY_REQUIRED = 'AVATAR_KEY_REQUIRED',
  AVATAR_KEY_INVALID = 'AVATAR_KEY_INVALID',

  VALIDATION_UNKNOWN = 'VALIDATION_UNKNOWN',
}
